[package]
name = "leifs/neworker"
description = "A replacement for RemoteEvents"
version = "0.1.0"
license = "MIT"
authors = ["Leif Stout <leifstout@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.3.0"